name: emakina_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  bloc: ^8.1.0
  build_runner: ^2.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  get_it: ^6.1.1
  flutter_native_splash: ^2.2.7
  flutter_svg: ^1.1.3


dev_dependencies:
  freezed: ^2.1.0+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  environment_config: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/bottomNavBar/
    - assets/projectData/
    - assets/projectPictures/
